import { NextFunction, Request, Response } from "express";

export const CustomerSignUp = async (req: Request, res: Response, next: NextFunction) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(200).json("Internal Server Error");
  }
};

export const CustomerLogin = async (req: Request, res: Response, next: NextFunction) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(200).json("Internal Server Error");
  }
};

export const CustomerVerification = async (req: Request, res: Response, next: NextFunction) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(200).json("Internal Server Error");
  }
};

export const getOtp = async (req: Request, res: Response, next: NextFunction) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(200).json("Internal Server Error");
  }
};

export const CustomerProfile = async (req: Request, res: Response, next: NextFunction) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(200).json("Internal Server Error");
  }
};

export const UpdateCustomerProfile = async (req: Request, res: Response, next: NextFunction) => {
  try {
  } catch (error) {
    console.log(error);
    return res.status(200).json("Internal Server Error");
  }
};
